package br.com.cuscrudrest.products;

import br.com.cuscrudrest.auth.jwt.IssuedJwtToken;
import br.com.cuscrudrest.auth.jwt.JwtService;
import br.com.cuscrudrest.auth.support.PasswordHasher;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.web.servlet.MockMvc;

import java.util.UUID;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "cuscrud.database.url=jdbc:h2:mem:get_product_endpoint;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "cuscrud.database.user=sa",
        "cuscrud.database.password=test",
        "cuscrud.auth.jwt-secret=test-jwt-secret-for-get-product"
})
@AutoConfigureMockMvc
class ProductsGetControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private PasswordHasher passwordHasher;

    @Autowired
    private JwtService jwtService;

    /**
     * Prepara o schema minimo antes de cada teste do endpoint de leitura unitaria de produto.
     * Entrada: nenhuma.
     * Esperado: tabelas recriadas vazias com schema compativel com o contrato da API.
     */
    @BeforeEach
    void setUp() {
        jdbcClient.sql("DROP TABLE IF EXISTS products").update();
        jdbcClient.sql("DROP TABLE IF EXISTS types").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventory_access").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventories").update();
        jdbcClient.sql("DROP TABLE IF EXISTS users").update();
        jdbcClient.sql("""
                CREATE TABLE users (
                    user_id UUID DEFAULT random_uuid() PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    login VARCHAR(255) UNIQUE NOT NULL,
                    passwd TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventories (
                    inv_id UUID PRIMARY KEY,
                    inv_name VARCHAR(255) NOT NULL
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventory_access (
                    user_id UUID NOT NULL,
                    inv_id UUID NOT NULL,
                    role INT NOT NULL,
                    PRIMARY KEY (user_id, inv_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE types (
                    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    imagem BYTEA NULL,
                    inv_id UUID NOT NULL,
                    UNIQUE (inv_id, type_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE products (
                    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    type_id BIGINT NOT NULL,
                    marca VARCHAR(255) NULL,
                    dataValidade TIMESTAMP WITH TIME ZONE NULL,
                    unidade BIGINT NULL,
                    unidadeMedida VARCHAR(255) NULL,
                    quantidade BIGINT NOT NULL DEFAULT 0,
                    inv_id UUID NOT NULL,
                    FOREIGN KEY (inv_id, type_id) REFERENCES types(inv_id, type_id) ON DELETE RESTRICT
                )
                """).update();
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/products/{product_id} retorna o produto para usuario com acesso.
     * Entrada: JWT valido para usuario com acesso ao inventario e produto persistido.
     * Esperado: status 200 com todos os campos previstos pela API.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnProductWhenAuthenticatedUserHasAccessToInventory() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 2);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(101L, 1L, "Acme", "2026-12-31T00:00:00-03:00", 1L, "un", 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(get("/inventories/{inv_id}/products/{product_id}", inventoryId, 101L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token()))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.product_id").value(101))
                .andExpect(jsonPath("$.type_id").value(1))
                .andExpect(jsonPath("$.marca").value("Acme"))
                .andExpect(jsonPath("$.dataValidade").value("2026-12-31T00:00:00-03:00"))
                .andExpect(jsonPath("$.unidade").value(1))
                .andExpect(jsonPath("$.unidadeMedida").value("un"))
                .andExpect(jsonPath("$.quantidade").value(50))
                .andExpect(jsonPath("$.inv_id").value(inventoryId.toString()));
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/products/{product_id} retorna campos opcionais nulos quando ausentes.
     * Entrada: JWT valido para usuario com acesso ao inventario e produto sem valores opcionais.
     * Esperado: status 200 com campos opcionais ausentes/nulos no JSON.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnNullOptionalFieldsWhenProductDoesNotPopulateThem() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(101L, 1L, null, null, null, null, 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(get("/inventories/{inv_id}/products/{product_id}", inventoryId, 101L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token()))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.marca").isEmpty())
                .andExpect(jsonPath("$.dataValidade").isEmpty())
                .andExpect(jsonPath("$.unidade").isEmpty())
                .andExpect(jsonPath("$.unidadeMedida").isEmpty());
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/products/{product_id} exige autenticacao.
     * Entrada: requisicao sem Authorization.
     * Esperado: status 401 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldRequireAuthenticationToGetProduct() throws Exception {
        mockMvc.perform(get("/inventories/{inv_id}/products/{product_id}", UUID.randomUUID(), 101L))
                .andExpect(status().isUnauthorized())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.error.code").value("UNAUTHENTICATED"))
                .andExpect(jsonPath("$.error.details.campo").value("Authorization"));
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/products/{product_id} rejeita inventario sem acesso.
     * Entrada: JWT valido para usuario sem vinculo com o inventario informado.
     * Esperado: status 404 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnNotFoundWhenInventoryDoesNotExistOrDoesNotBelongToUser() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(get("/inventories/{inv_id}/products/{product_id}", UUID.randomUUID(), 101L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token()))
                .andExpect(status().isNotFound())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.error.code").value("NOT_FOUND"))
                .andExpect(jsonPath("$.error.details.campo").value("inv_id"));
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/products/{product_id} rejeita `product_id` inexistente.
     * Entrada: JWT valido para usuario com acesso ao inventario e `product_id` ausente.
     * Esperado: status 404 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnNotFoundWhenProductDoesNotExist() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 0);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(get("/inventories/{inv_id}/products/{product_id}", inventoryId, 101L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token()))
                .andExpect(status().isNotFound())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.error.code").value("NOT_FOUND"))
                .andExpect(jsonPath("$.error.details.campo").value("product_id"));
    }

    private UUID insertUser(String name, String login, String rawPassword) {
        UUID userId = UUID.randomUUID();
        jdbcClient.sql("""
                INSERT INTO users (user_id, name, login, passwd)
                VALUES (:userId, :name, :login, :passwd)
                """)
                .param("userId", userId)
                .param("name", name)
                .param("login", login)
                .param("passwd", passwordHasher.hash(rawPassword))
                .update();
        return userId;
    }

    private void insertInventory(UUID inventoryId, String inventoryName) {
        jdbcClient.sql("""
                INSERT INTO inventories (inv_id, inv_name)
                VALUES (:inventoryId, :inventoryName)
                """)
                .param("inventoryId", inventoryId)
                .param("inventoryName", inventoryName)
                .update();
    }

    private void insertInventoryAccess(UUID userId, UUID inventoryId, int role) {
        jdbcClient.sql("""
                INSERT INTO inventory_access (user_id, inv_id, role)
                VALUES (:userId, :inventoryId, :role)
                """)
                .param("userId", userId)
                .param("inventoryId", inventoryId)
                .param("role", role)
                .update();
    }

    private void insertType(long typeId, String nome, UUID inventoryId) {
        jdbcClient.sql("""
                INSERT INTO types (type_id, nome, inv_id)
                VALUES (:typeId, :nome, :inventoryId)
                """)
                .param("typeId", typeId)
                .param("nome", nome)
                .param("inventoryId", inventoryId)
                .update();
    }

    private void insertProduct(
            long productId,
            long typeId,
            String marca,
            String dataValidade,
            Long unidade,
            String unidadeMedida,
            long quantidade,
            UUID inventoryId
    ) {
        jdbcClient.sql("""
                INSERT INTO products (
                    product_id, type_id, marca, dataValidade, unidade, unidadeMedida, quantidade, inv_id
                ) VALUES (
                    :productId, :typeId, :marca, :dataValidade, :unidade, :unidadeMedida, :quantidade, :inventoryId
                )
                """)
                .param("productId", productId)
                .param("typeId", typeId)
                .param("marca", marca)
                .param("dataValidade", dataValidade)
                .param("unidade", unidade)
                .param("unidadeMedida", unidadeMedida)
                .param("quantidade", quantidade)
                .param("inventoryId", inventoryId)
                .update();
    }
}
