package br.com.cuscrudrest.products;

import br.com.cuscrudrest.auth.jwt.IssuedJwtToken;
import br.com.cuscrudrest.auth.jwt.JwtService;
import br.com.cuscrudrest.auth.support.PasswordHasher;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.web.servlet.MockMvc;

import java.util.UUID;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "cuscrud.database.url=jdbc:h2:mem:update_product_endpoint;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "cuscrud.database.user=sa",
        "cuscrud.database.password=test",
        "cuscrud.auth.jwt-secret=test-jwt-secret-for-update-product"
})
@AutoConfigureMockMvc
class ProductsUpdateControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private PasswordHasher passwordHasher;

    @Autowired
    private JwtService jwtService;

    /**
     * Prepara o schema minimo antes de cada teste do endpoint de atualizacao de produtos.
     * Entrada: nenhuma.
     * Esperado: tabelas recriadas vazias com schema compativel com o contrato da API.
     */
    @BeforeEach
    void setUp() {
        jdbcClient.sql("DROP TABLE IF EXISTS products").update();
        jdbcClient.sql("DROP TABLE IF EXISTS types").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventory_access").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventories").update();
        jdbcClient.sql("DROP TABLE IF EXISTS users").update();
        jdbcClient.sql("""
                CREATE TABLE users (
                    user_id UUID DEFAULT random_uuid() PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    login VARCHAR(255) UNIQUE NOT NULL,
                    passwd TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventories (
                    inv_id UUID PRIMARY KEY,
                    inv_name VARCHAR(255) NOT NULL
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventory_access (
                    user_id UUID NOT NULL,
                    inv_id UUID NOT NULL,
                    role INT NOT NULL,
                    PRIMARY KEY (user_id, inv_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE types (
                    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    imagem BYTEA NULL,
                    inv_id UUID NOT NULL,
                    UNIQUE (inv_id, type_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE products (
                    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    type_id BIGINT NOT NULL,
                    marca VARCHAR(255) NULL,
                    dataValidade TIMESTAMP WITH TIME ZONE NULL,
                    unidade BIGINT NULL,
                    unidadeMedida VARCHAR(255) NULL,
                    quantidade BIGINT NOT NULL DEFAULT 0,
                    inv_id UUID NOT NULL,
                    FOREIGN KEY (inv_id, type_id) REFERENCES types(inv_id, type_id) ON DELETE RESTRICT
                )
                """).update();
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} atualiza o produto quando o usuario possui escrita.
     * Entrada: JWT valido para usuario editor, produto existente e payload parcial com troca de tipo e quantidade.
     * Esperado: status 200 com os dados atualizados do produto.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldUpdateProductWhenAuthenticatedUserHasWriteAccess() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(1L, "Bebidas", inventoryId);
        insertType(2L, "Congelados", inventoryId);
        insertProduct(301L, 1L, "Acme", "2026-12-31T00:00:00-03:00", 1L, "un", 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "type_id": 2,
                                  "quantidade": 75,
                                  "unidadeMedida": "cx"
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.product_id").value(301))
                .andExpect(jsonPath("$.type_id").value(2))
                .andExpect(jsonPath("$.marca").value("Acme"))
                .andExpect(jsonPath("$.dataValidade").value("2026-12-31T00:00:00-03:00"))
                .andExpect(jsonPath("$.unidade").value(1))
                .andExpect(jsonPath("$.unidadeMedida").value("cx"))
                .andExpect(jsonPath("$.quantidade").value(75))
                .andExpect(jsonPath("$.inv_id").value(inventoryId.toString()));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} permite limpar campos opcionais anulaveis.
     * Entrada: JWT valido, produto existente e payload com `marca`, `dataValidade`, `unidade` e `unidadeMedida` nulos.
     * Esperado: status 200 sem esses campos no JSON de resposta.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldClearNullableFieldsWhenPayloadUsesNull() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 0);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(301L, 1L, "Acme", "2026-12-31T00:00:00-03:00", 1L, "un", 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "marca": null,
                                  "dataValidade": null,
                                  "unidade": null,
                                  "unidadeMedida": null
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.marca").doesNotExist())
                .andExpect(jsonPath("$.dataValidade").doesNotExist())
                .andExpect(jsonPath("$.unidade").doesNotExist())
                .andExpect(jsonPath("$.unidadeMedida").doesNotExist())
                .andExpect(jsonPath("$.quantidade").value(50));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} exige autenticacao.
     * Entrada: requisicao sem Authorization.
     * Esperado: status 401 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldRequireAuthenticationToUpdateProduct() throws Exception {
        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", UUID.randomUUID(), 301L)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "quantidade": 10
                                }
                                """))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.error.code").value("UNAUTHENTICATED"))
                .andExpect(jsonPath("$.error.details.campo").value("Authorization"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} rejeita usuario apenas com role reader.
     * Entrada: JWT valido para usuario com `role = 2` no inventario.
     * Esperado: status 403 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnForbiddenWhenUserOnlyHasReaderAccess() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 2);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(301L, 1L, "Acme", null, null, null, 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "quantidade": 10
                                }
                                """))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.error.code").value("FORBIDDEN"))
                .andExpect(jsonPath("$.error.details.campo").value("inv_id"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} rejeita `product_id` inexistente.
     * Entrada: JWT valido para usuario com escrita no inventario e produto ausente.
     * Esperado: status 404 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnNotFoundWhenProductDoesNotExist() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "quantidade": 10
                                }
                                """))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.error.code").value("NOT_FOUND"))
                .andExpect(jsonPath("$.error.details.campo").value("product_id"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} rejeita `type_id` inexistente no inventario.
     * Entrada: JWT valido para usuario com escrita e payload apontando para tipo ausente.
     * Esperado: status 404 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnNotFoundWhenTypeDoesNotExistInInventory() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 0);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(301L, 1L, "Acme", null, null, null, 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "type_id": 99
                                }
                                """))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.error.code").value("NOT_FOUND"))
                .andExpect(jsonPath("$.error.details.campo").value("type_id"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} rejeita payload sem campos.
     * Entrada: JWT valido e corpo `{}`.
     * Esperado: status 400 no formato padrao de erro com campo `payload`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnValidationErrorWhenPatchHasNoFields() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(301L, 1L, "Acme", null, null, null, 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"))
                .andExpect(jsonPath("$.error.details.campo").value("payload"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} rejeita `quantidade` acima do teto aceito.
     * Entrada: JWT valido e `quantidade` maior que `999999999999999999`.
     * Esperado: status 400 no formato padrao de erro com campo `quantidade`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnBadRequestWhenQuantidadeExceedsMaximum() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(301L, 1L, "Acme", null, null, null, 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "quantidade": 1000000000000000000
                                }
                                """))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"))
                .andExpect(jsonPath("$.error.details.campo").value("quantidade"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} rejeita `unidade` acima do teto aceito.
     * Entrada: JWT valido e `unidade` maior que `999999999999999999`.
     * Esperado: status 400 no formato padrao de erro com campo `unidade`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnBadRequestWhenUnidadeExceedsMaximum() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(301L, 1L, "Acme", null, null, null, 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "unidade": 1000000000000000000
                                }
                                """))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"))
                .andExpect(jsonPath("$.error.details.campo").value("unidade"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/products/{product_id} rejeita formato invalido de campo.
     * Entrada: JWT valido e `dataValidade` nao parseavel.
     * Esperado: status 400 no formato padrao de erro com campo `dataValidade`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnBadRequestWhenPayloadHasInvalidFieldFormat() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 0);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(301L, 1L, "Acme", null, null, null, 50L, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/products/{product_id}", inventoryId, 301L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "dataValidade": "invalida"
                                }
                                """))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"))
                .andExpect(jsonPath("$.error.details.campo").value("dataValidade"));
    }

    private UUID insertUser(String name, String login, String rawPassword) {
        UUID userId = UUID.randomUUID();
        jdbcClient.sql("""
                INSERT INTO users (user_id, name, login, passwd)
                VALUES (:userId, :name, :login, :passwd)
                """)
                .param("userId", userId)
                .param("name", name)
                .param("login", login)
                .param("passwd", passwordHasher.hash(rawPassword))
                .update();
        return userId;
    }

    private void insertInventory(UUID inventoryId, String inventoryName) {
        jdbcClient.sql("""
                INSERT INTO inventories (inv_id, inv_name)
                VALUES (:inventoryId, :inventoryName)
                """)
                .param("inventoryId", inventoryId)
                .param("inventoryName", inventoryName)
                .update();
    }

    private void insertInventoryAccess(UUID userId, UUID inventoryId, int role) {
        jdbcClient.sql("""
                INSERT INTO inventory_access (user_id, inv_id, role)
                VALUES (:userId, :inventoryId, :role)
                """)
                .param("userId", userId)
                .param("inventoryId", inventoryId)
                .param("role", role)
                .update();
    }

    private void insertType(long typeId, String nome, UUID inventoryId) {
        jdbcClient.sql("""
                INSERT INTO types (type_id, nome, inv_id)
                VALUES (:typeId, :nome, :inventoryId)
                """)
                .param("typeId", typeId)
                .param("nome", nome)
                .param("inventoryId", inventoryId)
                .update();
    }

    private void insertProduct(
            long productId,
            long typeId,
            String marca,
            String dataValidade,
            Long unidade,
            String unidadeMedida,
            long quantidade,
            UUID inventoryId
    ) {
        jdbcClient.sql("""
                INSERT INTO products (
                    product_id, type_id, marca, dataValidade, unidade, unidadeMedida, quantidade, inv_id
                ) VALUES (
                    :productId, :typeId, :marca, :dataValidade, :unidade, :unidadeMedida, :quantidade, :inventoryId
                )
                """)
                .param("productId", productId)
                .param("typeId", typeId)
                .param("marca", marca)
                .param("dataValidade", dataValidade != null ? java.time.OffsetDateTime.parse(dataValidade) : null)
                .param("unidade", unidade)
                .param("unidadeMedida", unidadeMedida)
                .param("quantidade", quantidade)
                .param("inventoryId", inventoryId)
                .update();
    }
}
