package br.com.cuscrudrest.types.get;

import br.com.cuscrudrest.auth.security.AuthenticatedUserPrincipal;
import br.com.cuscrudrest.common.error.NotFoundException;
import br.com.cuscrudrest.inventories.InventoryAccessService;
import br.com.cuscrudrest.inventories.InventoryRepository;
import br.com.cuscrudrest.types.TypeRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.time.OffsetDateTime;
import java.util.Base64;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class GetTypeServiceTest {

    private JdbcClient jdbcClient;
    private GetTypeService getTypeService;
    private AuthenticatedUserPrincipal authenticatedUser;

    /**
     * Prepara o schema minimo e as dependencias reais do servico de leitura unitaria de tipos.
     * Entrada: nenhuma.
     * Esperado: servico pronto para buscar um tipo de inventario acessivel.
     */
    @BeforeEach
    void setUp() {
        DataSource dataSource = createDataSource();
        jdbcClient = JdbcClient.create(dataSource);
        jdbcClient.sql("DROP TABLE IF EXISTS types").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventory_access").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventories").update();
        jdbcClient.sql("DROP TABLE IF EXISTS users").update();
        jdbcClient.sql("""
                CREATE TABLE users (
                    user_id UUID PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    login VARCHAR(255) UNIQUE NOT NULL,
                    passwd TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventories (
                    inv_id UUID PRIMARY KEY,
                    inv_name VARCHAR(255) NOT NULL
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventory_access (
                    user_id UUID NOT NULL,
                    inv_id UUID NOT NULL,
                    role INT NOT NULL,
                    PRIMARY KEY (user_id, inv_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE types (
                    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    imagem BYTEA NULL,
                    inv_id UUID NOT NULL
                )
                """).update();

        UUID userId = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
        insertUser(userId, "Joao Silva", "joao@example.com");
        authenticatedUser = new AuthenticatedUserPrincipal(
                userId,
                "Joao Silva",
                "joao@example.com",
                OffsetDateTime.parse("2026-03-25T10:00:00-03:00"),
                OffsetDateTime.parse("2026-03-25T10:00:00-03:00"),
                OffsetDateTime.parse("2026-03-25T11:00:00-03:00"),
                3600
        );

        InventoryRepository inventoryRepository = new InventoryRepository(jdbcClient);
        getTypeService = new GetTypeService(
                new InventoryAccessService(inventoryRepository),
                new TypeRepository(jdbcClient)
        );
    }

    /**
     * Verifica que o servico retorna um tipo especifico serializando a imagem para data URI.
     * Entrada: inventario acessivel com tipo contendo bytes em `imagem`.
     * Esperado: resposta com `imagem` no formato `data:image/png;base64,...`.
     */
    @Test
    void shouldReturnTypeWithImageSerializedAsDataUri() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        byte[] imageBytes = new byte[]{1, 2, 3, 4};
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 2);
        insertType(1L, "Bebidas", imageBytes, inventoryId);

        GetTypeResponse response = getTypeService.getType(authenticatedUser, inventoryId, 1L);

        assertEquals(1L, response.typeId());
        assertEquals("Bebidas", response.nome());
        assertEquals(
                "data:image/png;base64," + Base64.getEncoder().encodeToString(imageBytes),
                response.imagem()
        );
        assertEquals(inventoryId, response.inventoryId());
    }

    /**
     * Verifica que o servico retorna `imagem = null` quando o tipo nao possui imagem persistida.
     * Entrada: inventario acessivel com tipo sem bytes de imagem.
     * Esperado: resposta com `imagem = null`.
     */
    @Test
    void shouldReturnNullImageWhenTypeDoesNotHaveImage() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 1);
        insertType(1L, "Bebidas", null, inventoryId);

        GetTypeResponse response = getTypeService.getType(authenticatedUser, inventoryId, 1L);

        assertNull(response.imagem());
    }

    /**
     * Verifica que o servico rejeita inventario sem acesso para o usuario autenticado.
     * Entrada: inventario existente sem vinculo do usuario autenticado.
     * Esperado: NotFoundException associada ao campo `inv_id`.
     */
    @Test
    void shouldRejectWhenAuthenticatedUserDoesNotBelongToInventory() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");

        NotFoundException exception = assertThrows(
                NotFoundException.class,
                () -> getTypeService.getType(authenticatedUser, inventoryId, 1L)
        );

        assertEquals("inv_id", exception.getCampo());
        assertEquals("inventory not found", exception.getInfo());
    }

    /**
     * Verifica que o servico rejeita `type_id` inexistente para o inventario informado.
     * Entrada: inventario acessivel sem tipo correspondente.
     * Esperado: NotFoundException associada ao campo `type_id`.
     */
    @Test
    void shouldRejectWhenTypeDoesNotExist() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 0);

        NotFoundException exception = assertThrows(
                NotFoundException.class,
                () -> getTypeService.getType(authenticatedUser, inventoryId, 1L)
        );

        assertEquals("type_id", exception.getCampo());
        assertEquals("type not found", exception.getInfo());
    }

    private void insertUser(UUID userId, String name, String login) {
        jdbcClient.sql("""
                INSERT INTO users (user_id, name, login, passwd)
                VALUES (:userId, :name, :login, :passwd)
                """)
                .param("userId", userId)
                .param("name", name)
                .param("login", login)
                .param("passwd", "$2a$10$abcdefghijklmnopqrstuv")
                .update();
    }

    private void insertInventory(UUID inventoryId, String inventoryName) {
        jdbcClient.sql("""
                INSERT INTO inventories (inv_id, inv_name)
                VALUES (:inventoryId, :inventoryName)
                """)
                .param("inventoryId", inventoryId)
                .param("inventoryName", inventoryName)
                .update();
    }

    private void insertInventoryAccess(UUID userId, UUID inventoryId, int role) {
        jdbcClient.sql("""
                INSERT INTO inventory_access (user_id, inv_id, role)
                VALUES (:userId, :inventoryId, :role)
                """)
                .param("userId", userId)
                .param("inventoryId", inventoryId)
                .param("role", role)
                .update();
    }

    private void insertType(long typeId, String nome, byte[] imagem, UUID inventoryId) {
        jdbcClient.sql("""
                INSERT INTO types (type_id, nome, imagem, inv_id)
                VALUES (:typeId, :nome, :imagem, :inventoryId)
                """)
                .param("typeId", typeId)
                .param("nome", nome)
                .param("imagem", imagem)
                .param("inventoryId", inventoryId)
                .update();
    }

    private DataSource createDataSource() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:get_type_service;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("test");
        return dataSource;
    }
}
