package com.cuscrud

import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.ViewModel
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.viewModelScope
import com.cuscrud.domain.model.Produto
import com.cuscrud.domain.model.Tipo
import com.cuscrud.domain.repository.ProdutoRepository
import com.cuscrud.domain.repository.TipoRepository
import dagger.hilt.android.AndroidEntryPoint
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.util.Date
import javax.inject.Inject

@AndroidEntryPoint
class MainActivity : AppCompatActivity() {

    private val viewModel: MainViewModel by viewModels()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val statusText = findViewById<TextView>(R.id.statusText)
        val testButton = findViewById<Button>(R.id.testButton)

        // Observe data from the database
        lifecycleScope.launch {
            viewModel.produtos.collect { list ->
                if (list.isEmpty()) {
                    statusText.text = "No products in database. Click to add one!"
                } else {
                    val last = list.last()
                    statusText.text = "Last added: ${last.marca} (${last.tipo.nome})\nTotal count: ${list.size}"
                }
            }
        }

        testButton.setOnClickListener {
            viewModel.addSampleProduct()
        }
    }
}

@HiltViewModel
class MainViewModel @Inject constructor(
    private val produtoRepository: ProdutoRepository,
    private val tipoRepository: TipoRepository
) : ViewModel() {

    // Expose products list as a StateFlow
    val produtos: StateFlow<List<Produto>> = produtoRepository.getAllProdutos()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = emptyList()
        )

    fun addSampleProduct() {
        viewModelScope.launch {
            // 1. Ensure we have at least one type
            val sampleTipo = Tipo(id = 1L, nome = "Eletrônicos", imagem = byteArrayOf(0x01))
            tipoRepository.insertTipo(sampleTipo)

            // 2. Add a product using that type
            val newProduto = Produto(
                id = 0, // Auto-generated by Room
                tipo = sampleTipo,
                marca = "Brand ${System.currentTimeMillis() % 1000}",
                dataValidade = Date(),
                unidade = 1,
                unidadeMedida = "un",
                quantidade = (1..100).random().toLong()
            )
            produtoRepository.insertProduto(newProduto)
        }
    }
}
