package br.com.cuscrudrest.products.create;

import br.com.cuscrudrest.auth.security.AuthenticatedUserPrincipal;
import br.com.cuscrudrest.common.error.NotFoundException;
import br.com.cuscrudrest.inventories.InventoryAccessService;
import br.com.cuscrudrest.inventories.InventoryRepository;
import br.com.cuscrudrest.products.ProductRepository;
import br.com.cuscrudrest.types.TypeRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.time.OffsetDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class CreateProductServiceTest {

    private JdbcClient jdbcClient;
    private CreateProductService createProductService;
    private AuthenticatedUserPrincipal authenticatedUser;

    /**
     * Prepara o schema minimo e as dependencias reais do servico de criacao de produtos.
     * Entrada: nenhuma.
     * Esperado: servico pronto para criar produtos em inventarios acessiveis para escrita.
     */
    @BeforeEach
    void setUp() {
        DataSource dataSource = createDataSource();
        jdbcClient = JdbcClient.create(dataSource);
        jdbcClient.sql("DROP TABLE IF EXISTS products").update();
        jdbcClient.sql("DROP TABLE IF EXISTS types").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventory_access").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventories").update();
        jdbcClient.sql("DROP TABLE IF EXISTS users").update();
        jdbcClient.sql("""
                CREATE TABLE users (
                    user_id UUID PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    login VARCHAR(255) UNIQUE NOT NULL,
                    passwd TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventories (
                    inv_id UUID PRIMARY KEY,
                    inv_name VARCHAR(255) NOT NULL
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventory_access (
                    user_id UUID NOT NULL,
                    inv_id UUID NOT NULL,
                    role INT NOT NULL,
                    PRIMARY KEY (user_id, inv_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE types (
                    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    imagem BYTEA NULL,
                    inv_id UUID NOT NULL,
                    UNIQUE (inv_id, type_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE products (
                    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    type_id BIGINT NOT NULL,
                    marca VARCHAR(255) NULL,
                    dataValidade TIMESTAMP WITH TIME ZONE NULL,
                    unidade BIGINT NULL,
                    unidadeMedida VARCHAR(255) NULL,
                    quantidade BIGINT NOT NULL DEFAULT 0,
                    inv_id UUID NOT NULL,
                    FOREIGN KEY (inv_id, type_id) REFERENCES types(inv_id, type_id) ON DELETE RESTRICT
                )
                """).update();

        UUID userId = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
        insertUser(userId, "Joao Silva", "joao@example.com");
        authenticatedUser = new AuthenticatedUserPrincipal(
                userId,
                "Joao Silva",
                "joao@example.com",
                OffsetDateTime.parse("2026-03-25T10:00:00-03:00"),
                OffsetDateTime.parse("2026-03-25T10:00:00-03:00"),
                OffsetDateTime.parse("2026-03-25T11:00:00-03:00"),
                3600
        );

        InventoryRepository inventoryRepository = new InventoryRepository(jdbcClient);
        createProductService = new CreateProductService(
                new InventoryAccessService(inventoryRepository),
                new ProductRepository(jdbcClient, new NamedParameterJdbcTemplate(dataSource)),
                new TypeRepository(jdbcClient)
        );
    }

    /**
     * Verifica que o servico cria um produto e aplica `quantidade = 0` quando o campo nao e informado.
     * Entrada: inventario acessivel para escrita, tipo existente e payload sem `quantidade`.
     * Esperado: resposta com `product_id` gerado e `quantidade = 0`.
     */
    @Test
    void shouldCreateProductWithDefaultQuantityWhenNotProvided() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        OffsetDateTime validade = OffsetDateTime.parse("2026-12-31T00:00:00-03:00");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 1);
        insertType(1L, "Bebidas", inventoryId);

        CreateProductResponse response = createProductService.createProduct(
                authenticatedUser,
                inventoryId,
                new CreateProductRequest(1L, "Acme", validade, 1L, "un", null)
        );

        assertEquals(1L, response.typeId());
        assertEquals("Acme", response.marca());
        assertEquals(validade, response.dataValidade());
        assertEquals(1L, response.unidade());
        assertEquals("un", response.unidadeMedida());
        assertEquals(0L, response.quantidade());
        assertEquals(inventoryId, response.inventoryId());
    }

    /**
     * Verifica que o servico preserva campos opcionais nulos quando o payload nao os informa.
     * Entrada: inventario acessivel para escrita, tipo existente e payload minimo.
     * Esperado: resposta com campos opcionais nulos e quantidade default.
     */
    @Test
    void shouldCreateProductWithNullOptionalFields() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 0);
        insertType(1L, "Bebidas", inventoryId);

        CreateProductResponse response = createProductService.createProduct(
                authenticatedUser,
                inventoryId,
                new CreateProductRequest(1L, null, null, null, null, null)
        );

        assertNull(response.marca());
        assertNull(response.dataValidade());
        assertNull(response.unidade());
        assertNull(response.unidadeMedida());
        assertEquals(0L, response.quantidade());
    }

    /**
     * Verifica que o servico rejeita `type_id` inexistente para o inventario informado.
     * Entrada: inventario acessivel para escrita sem tipo correspondente.
     * Esperado: NotFoundException associada ao campo `type_id`.
     */
    @Test
    void shouldRejectWhenTypeDoesNotExistInInventory() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 0);

        NotFoundException exception = assertThrows(
                NotFoundException.class,
                () -> createProductService.createProduct(
                        authenticatedUser,
                        inventoryId,
                        new CreateProductRequest(1L, "Acme", null, null, null, 5L)
                )
        );

        assertEquals("type_id", exception.getCampo());
        assertEquals("type not found", exception.getInfo());
    }

    private void insertUser(UUID userId, String name, String login) {
        jdbcClient.sql("""
                INSERT INTO users (user_id, name, login, passwd)
                VALUES (:userId, :name, :login, :passwd)
                """)
                .param("userId", userId)
                .param("name", name)
                .param("login", login)
                .param("passwd", "$2a$10$abcdefghijklmnopqrstuv")
                .update();
    }

    private void insertInventory(UUID inventoryId, String inventoryName) {
        jdbcClient.sql("""
                INSERT INTO inventories (inv_id, inv_name)
                VALUES (:inventoryId, :inventoryName)
                """)
                .param("inventoryId", inventoryId)
                .param("inventoryName", inventoryName)
                .update();
    }

    private void insertInventoryAccess(UUID userId, UUID inventoryId, int role) {
        jdbcClient.sql("""
                INSERT INTO inventory_access (user_id, inv_id, role)
                VALUES (:userId, :inventoryId, :role)
                """)
                .param("userId", userId)
                .param("inventoryId", inventoryId)
                .param("role", role)
                .update();
    }

    private void insertType(long typeId, String nome, UUID inventoryId) {
        jdbcClient.sql("""
                INSERT INTO types (type_id, nome, inv_id)
                VALUES (:typeId, :nome, :inventoryId)
                """)
                .param("typeId", typeId)
                .param("nome", nome)
                .param("inventoryId", inventoryId)
                .update();
    }

    private DataSource createDataSource() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:create_product_service;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("test");
        return dataSource;
    }
}
