package br.com.cuscrudrest.types;

import br.com.cuscrudrest.auth.jwt.IssuedJwtToken;
import br.com.cuscrudrest.auth.jwt.JwtService;
import br.com.cuscrudrest.auth.support.PasswordHasher;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.web.servlet.MockMvc;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.UUID;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "cuscrud.database.url=jdbc:h2:mem:update_type_endpoint;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "cuscrud.database.user=sa",
        "cuscrud.database.password=test",
        "cuscrud.auth.jwt-secret=test-jwt-secret-for-update-type"
})
@AutoConfigureMockMvc
class TypesUpdateControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private PasswordHasher passwordHasher;

    @Autowired
    private JwtService jwtService;

    /**
     * Prepara o schema minimo antes de cada teste do endpoint de atualizacao de tipos.
     * Entrada: nenhuma.
     * Esperado: tabelas recriadas vazias com schema compativel com o contrato da API.
     */
    @BeforeEach
    void setUp() {
        jdbcClient.sql("DROP TABLE IF EXISTS types").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventory_access").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventories").update();
        jdbcClient.sql("DROP TABLE IF EXISTS users").update();
        jdbcClient.sql("""
                CREATE TABLE users (
                    user_id UUID DEFAULT random_uuid() PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    login VARCHAR(255) UNIQUE NOT NULL,
                    passwd TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventories (
                    inv_id UUID PRIMARY KEY,
                    inv_name VARCHAR(255) NOT NULL
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventory_access (
                    user_id UUID NOT NULL,
                    inv_id UUID NOT NULL,
                    role INT NOT NULL,
                    PRIMARY KEY (user_id, inv_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE types (
                    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    imagem BYTEA NULL,
                    inv_id UUID NOT NULL,
                    CONSTRAINT uq_types_inv_nome UNIQUE (inv_id, nome)
                )
                """).update();
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/types/{type_id} atualiza o tipo quando o usuario possui escrita.
     * Entrada: JWT valido, inventario acessivel com `role = 1`, tipo existente e payload com nome e imagem validos.
     * Esperado: status 200 com os dados atualizados do tipo.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldUpdateTypeWhenAuthenticatedUserHasWriteAccess() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        byte[] imageBytes = "png-bytes".getBytes(StandardCharsets.UTF_8);
        String imageDataUri = "data:image/png;base64," + Base64.getEncoder().encodeToString(imageBytes);
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(10L, "Higiene", "old".getBytes(StandardCharsets.UTF_8), inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/types/{type_id}", inventoryId, 10L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "nome": "Higiene e Limpeza",
                                  "imagem": "%s"
                                }
                                """.formatted(imageDataUri)))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.type_id").value(10))
                .andExpect(jsonPath("$.nome").value("Higiene e Limpeza"))
                .andExpect(jsonPath("$.imagem").value(imageDataUri))
                .andExpect(jsonPath("$.inv_id").value(inventoryId.toString()));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/types/{type_id} remove a imagem quando `imagem = null`.
     * Entrada: JWT valido, tipo existente com bytes de imagem persistidos e payload contendo `imagem: null`.
     * Esperado: status 200 com `imagem = null`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldRemoveImageWhenImagemIsNull() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 0);
        insertType(10L, "Higiene", "old".getBytes(StandardCharsets.UTF_8), inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/types/{type_id}", inventoryId, 10L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "imagem": null
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.imagem").doesNotExist());
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/types/{type_id} exige autenticacao.
     * Entrada: requisicao sem Authorization.
     * Esperado: status 401 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldRequireAuthenticationToUpdateType() throws Exception {
        mockMvc.perform(patch("/inventories/{inv_id}/types/{type_id}", UUID.randomUUID(), 10L)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "nome": "Higiene"
                                }
                                """))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.error.code").value("UNAUTHENTICATED"))
                .andExpect(jsonPath("$.error.details.campo").value("Authorization"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/types/{type_id} rejeita usuario apenas com role reader.
     * Entrada: JWT valido para usuario com `role = 2` no inventario.
     * Esperado: status 403 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnForbiddenWhenUserOnlyHasReaderAccess() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 2);
        insertType(10L, "Higiene", null, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/types/{type_id}", inventoryId, 10L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "nome": "Higiene e Limpeza"
                                }
                                """))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.error.code").value("FORBIDDEN"))
                .andExpect(jsonPath("$.error.details.campo").value("inv_id"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/types/{type_id} rejeita `type_id` inexistente.
     * Entrada: JWT valido para usuario com escrita no inventario e `type_id` ausente.
     * Esperado: status 404 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnNotFoundWhenTypeDoesNotExist() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/types/{type_id}", inventoryId, 10L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "nome": "Higiene e Limpeza"
                                }
                                """))
                .andExpect(status().isNotFound())
                .andExpect(jsonPath("$.error.code").value("NOT_FOUND"))
                .andExpect(jsonPath("$.error.details.campo").value("type_id"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/types/{type_id} rejeita payload sem campos.
     * Entrada: JWT valido e corpo `{}`.
     * Esperado: status 400 no formato padrao de erro com campo `payload`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnValidationErrorWhenPatchHasNoFields() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(10L, "Higiene", null, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/types/{type_id}", inventoryId, 10L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"))
                .andExpect(jsonPath("$.error.details.campo").value("payload"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/types/{type_id} rejeita imagem fora do formato data URI.
     * Entrada: JWT valido e payload com `imagem` textual invalida.
     * Esperado: status 400 no formato padrao de erro com campo `imagem`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnValidationErrorWhenImageIsInvalid() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(10L, "Higiene", null, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/types/{type_id}", inventoryId, 10L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "imagem": "imagem-invalida"
                                }
                                """))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"))
                .andExpect(jsonPath("$.error.details.campo").value("imagem"));
    }

    /**
     * Verifica que PATCH /api/v1/inventories/{inv_id}/types/{type_id} rejeita nome duplicado no mesmo inventario.
     * Entrada: JWT valido, tipo alvo existente e outro tipo do inventario com o nome solicitado.
     * Esperado: status 409 no formato padrao de erro com campo `nome`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnConflictWhenAnotherTypeWithSameNameExists() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(10L, "Higiene", null, inventoryId);
        insertType(11L, "Alimentos", null, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(patch("/inventories/{inv_id}/types/{type_id}", inventoryId, 10L)
                        .header("Authorization", "Bearer " + issuedJwtToken.token())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "nome": "Alimentos"
                                }
                                """))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.error.code").value("CONFLICT"))
                .andExpect(jsonPath("$.error.details.campo").value("nome"));
    }

    /**
     * Persiste um usuario de teste.
     *
     * @param name nome do usuario.
     * @param login email do usuario.
     * @param rawPassword senha em texto puro a ser hashada.
     * @return identificador do usuario inserido.
     */
    private UUID insertUser(String name, String login, String rawPassword) {
        UUID userId = UUID.randomUUID();
        jdbcClient.sql("""
                INSERT INTO users (user_id, name, login, passwd)
                VALUES (:userId, :name, :login, :passwd)
                """)
                .param("userId", userId)
                .param("name", name)
                .param("login", login)
                .param("passwd", passwordHasher.hash(rawPassword))
                .update();
        return userId;
    }

    /**
     * Persiste um inventario de teste.
     *
     * @param inventoryId identificador do inventario.
     * @param inventoryName nome do inventario.
     */
    private void insertInventory(UUID inventoryId, String inventoryName) {
        jdbcClient.sql("""
                INSERT INTO inventories (inv_id, inv_name)
                VALUES (:inventoryId, :inventoryName)
                """)
                .param("inventoryId", inventoryId)
                .param("inventoryName", inventoryName)
                .update();
    }

    /**
     * Persiste um vinculo de acesso de teste.
     *
     * @param userId identificador do usuario.
     * @param inventoryId identificador do inventario.
     * @param role role do usuario no inventario.
     */
    private void insertInventoryAccess(UUID userId, UUID inventoryId, int role) {
        jdbcClient.sql("""
                INSERT INTO inventory_access (user_id, inv_id, role)
                VALUES (:userId, :inventoryId, :role)
                """)
                .param("userId", userId)
                .param("inventoryId", inventoryId)
                .param("role", role)
                .update();
    }

    /**
     * Persiste um tipo de teste.
     *
     * @param typeId identificador do tipo.
     * @param nome nome do tipo.
     * @param imagem bytes da imagem, quando houver.
     * @param inventoryId identificador do inventario ao qual o tipo pertence.
     */
    private void insertType(long typeId, String nome, byte[] imagem, UUID inventoryId) {
        jdbcClient.sql("""
                INSERT INTO types (type_id, nome, imagem, inv_id)
                VALUES (:typeId, :nome, :imagem, :inventoryId)
                """)
                .param("typeId", typeId)
                .param("nome", nome)
                .param("imagem", imagem)
                .param("inventoryId", inventoryId)
                .update();
    }
}
