package br.com.cuscrudrest.types;

import br.com.cuscrudrest.auth.jwt.IssuedJwtToken;
import br.com.cuscrudrest.auth.jwt.JwtService;
import br.com.cuscrudrest.auth.support.PasswordHasher;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.web.servlet.MockMvc;

import java.util.UUID;

import static org.hamcrest.Matchers.endsWith;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "cuscrud.database.url=jdbc:h2:mem:list_types_endpoint;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
        "cuscrud.database.user=sa",
        "cuscrud.database.password=test",
        "cuscrud.auth.jwt-secret=test-jwt-secret-for-list-types"
})
@AutoConfigureMockMvc
class TypesListControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcClient jdbcClient;

    @Autowired
    private PasswordHasher passwordHasher;

    @Autowired
    private JwtService jwtService;

    /**
     * Prepara o schema minimo antes de cada teste do endpoint de listagem de tipos.
     * Entrada: nenhuma.
     * Esperado: tabelas recriadas vazias com schema compativel com o contrato da API.
     */
    @BeforeEach
    void setUp() {
        jdbcClient.sql("DROP TABLE IF EXISTS types").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventory_access").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventories").update();
        jdbcClient.sql("DROP TABLE IF EXISTS users").update();
        jdbcClient.sql("""
                CREATE TABLE users (
                    user_id UUID DEFAULT random_uuid() PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    login VARCHAR(255) UNIQUE NOT NULL,
                    passwd TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventories (
                    inv_id UUID PRIMARY KEY,
                    inv_name VARCHAR(255) NOT NULL
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventory_access (
                    user_id UUID NOT NULL,
                    inv_id UUID NOT NULL,
                    role INT NOT NULL,
                    PRIMARY KEY (user_id, inv_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE types (
                    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    imagem BYTEA NULL,
                    inv_id UUID NOT NULL
                )
                """).update();
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/types lista os tipos para usuario com role `2`.
     * Entrada: JWT valido para usuario com acesso reader ao inventario e dois tipos persistidos.
     * Esperado: status 200 com itens ordenados e sem `next_page`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldListTypesWhenAuthenticatedUserHasReaderAccess() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 2);
        insertType(2L, "Alimentos", false, inventoryId);
        insertType(1L, "Bebidas", true, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(get("/inventories/{inv_id}/types", inventoryId)
                        .header("Authorization", "Bearer " + issuedJwtToken.token()))
                .andExpect(status().isOk())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.types[0].type_id").value(1))
                .andExpect(jsonPath("$.types[0].nome").value("Bebidas"))
                .andExpect(jsonPath("$.types[0].has_image").value(true))
                .andExpect(jsonPath("$.types[1].type_id").value(2))
                .andExpect(jsonPath("$.types[1].has_image").value(false))
                .andExpect(jsonPath("$.next_page").doesNotExist());
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/types inclui `next_page` quando houver mais resultados.
     * Entrada: JWT valido, inventario acessivel e query `limit = 1`.
     * Esperado: status 200 com um item e `next_page` apontando para `offset=1&limit=1`.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldIncludeNextPageWhenThereAreMoreTypes() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 1);
        insertType(1L, "Bebidas", true, inventoryId);
        insertType(2L, "Alimentos", false, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(get("/inventories/{inv_id}/types", inventoryId)
                        .queryParam("limit", "1")
                        .queryParam("offset", "0")
                        .header("Authorization", "Bearer " + issuedJwtToken.token()))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.types.length()").value(1))
                .andExpect(jsonPath("$.next_page").value(
                        endsWith("/inventories/" + inventoryId + "/types?offset=1&limit=1")
                ));
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/types exige autenticacao.
     * Entrada: requisicao sem Authorization.
     * Esperado: status 401 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldRequireAuthenticationToListTypes() throws Exception {
        mockMvc.perform(get("/inventories/{inv_id}/types", UUID.randomUUID()))
                .andExpect(status().isUnauthorized())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.error.code").value("UNAUTHENTICATED"))
                .andExpect(jsonPath("$.error.details.campo").value("Authorization"));
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/types rejeita inventario sem acesso.
     * Entrada: JWT valido para usuario sem vinculo com o inventario informado.
     * Esperado: status 404 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnNotFoundWhenInventoryDoesNotExistOrDoesNotBelongToUser() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(get("/inventories/{inv_id}/types", UUID.randomUUID())
                        .header("Authorization", "Bearer " + issuedJwtToken.token()))
                .andExpect(status().isNotFound())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.error.code").value("NOT_FOUND"))
                .andExpect(jsonPath("$.error.details.campo").value("inv_id"));
    }

    /**
     * Verifica que GET /api/v1/inventories/{inv_id}/types rejeita `offset` apos o fim da lista.
     * Entrada: JWT valido e inventario com um unico tipo.
     * Esperado: status 404 no formato padrao de erro.
     *
     * @throws Exception quando a execucao do request de teste falha.
     */
    @Test
    void shouldReturnNotFoundWhenOffsetIsAfterEndOfList() throws Exception {
        UUID userId = insertUser("Joao Novo", "joao.novo@example.com", "senhaforte456");
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(userId, inventoryId, 0);
        insertType(1L, "Bebidas", true, inventoryId);
        IssuedJwtToken issuedJwtToken = jwtService.issueToken(userId);

        mockMvc.perform(get("/inventories/{inv_id}/types", inventoryId)
                        .queryParam("offset", "1")
                        .header("Authorization", "Bearer " + issuedJwtToken.token()))
                .andExpect(status().isNotFound())
                .andExpect(content().contentTypeCompatibleWith(MediaType.APPLICATION_JSON))
                .andExpect(jsonPath("$.error.code").value("NOT_FOUND"))
                .andExpect(jsonPath("$.error.details.campo").value("offset"));
    }

    private UUID insertUser(String name, String login, String rawPassword) {
        UUID userId = UUID.randomUUID();
        jdbcClient.sql("""
                INSERT INTO users (user_id, name, login, passwd)
                VALUES (:userId, :name, :login, :passwd)
                """)
                .param("userId", userId)
                .param("name", name)
                .param("login", login)
                .param("passwd", passwordHasher.hash(rawPassword))
                .update();
        return userId;
    }

    private void insertInventory(UUID inventoryId, String inventoryName) {
        jdbcClient.sql("""
                INSERT INTO inventories (inv_id, inv_name)
                VALUES (:inventoryId, :inventoryName)
                """)
                .param("inventoryId", inventoryId)
                .param("inventoryName", inventoryName)
                .update();
    }

    private void insertInventoryAccess(UUID userId, UUID inventoryId, int role) {
        jdbcClient.sql("""
                INSERT INTO inventory_access (user_id, inv_id, role)
                VALUES (:userId, :inventoryId, :role)
                """)
                .param("userId", userId)
                .param("inventoryId", inventoryId)
                .param("role", role)
                .update();
    }

    private void insertType(long typeId, String nome, boolean hasImage, UUID inventoryId) {
        jdbcClient.sql("""
                INSERT INTO types (type_id, nome, imagem, inv_id)
                VALUES (:typeId, :nome, :imagem, :inventoryId)
                """)
                .param("typeId", typeId)
                .param("nome", nome)
                .param("imagem", hasImage ? new byte[]{1, 2, 3} : null)
                .param("inventoryId", inventoryId)
                .update();
    }
}
