/home/alquimas/projects/CusCrudREST/backend/logs/cuscrud-backend.log /home/alquimas/projects/CusCrudREST/backend/logs/cuscrud-backend-application.log {
    size 10M
    rotate 10
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
