package br.com.cuscrudrest.types.list;

import br.com.cuscrudrest.auth.security.AuthenticatedUserPrincipal;
import br.com.cuscrudrest.common.error.NotFoundException;
import br.com.cuscrudrest.inventories.InventoryAccessService;
import br.com.cuscrudrest.inventories.InventoryRepository;
import br.com.cuscrudrest.types.TypeRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class ListTypesServiceTest {

    private JdbcClient jdbcClient;
    private ListTypesService listTypesService;
    private AuthenticatedUserPrincipal authenticatedUser;

    /**
     * Prepara o schema minimo e as dependencias reais do servico de listagem de tipos.
     * Entrada: nenhuma.
     * Esperado: servico pronto para listar tipos de inventarios acessiveis.
     */
    @BeforeEach
    void setUp() {
        DataSource dataSource = createDataSource();
        jdbcClient = JdbcClient.create(dataSource);
        jdbcClient.sql("DROP TABLE IF EXISTS types").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventory_access").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventories").update();
        jdbcClient.sql("DROP TABLE IF EXISTS users").update();
        jdbcClient.sql("""
                CREATE TABLE users (
                    user_id UUID PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    login VARCHAR(255) UNIQUE NOT NULL,
                    passwd TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventories (
                    inv_id UUID PRIMARY KEY,
                    inv_name VARCHAR(255) NOT NULL
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventory_access (
                    user_id UUID NOT NULL,
                    inv_id UUID NOT NULL,
                    role INT NOT NULL,
                    PRIMARY KEY (user_id, inv_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE types (
                    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    imagem BYTEA NULL,
                    inv_id UUID NOT NULL
                )
                """).update();

        UUID userId = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
        insertUser(userId, "Joao Silva", "joao@example.com");
        authenticatedUser = new AuthenticatedUserPrincipal(
                userId,
                "Joao Silva",
                "joao@example.com",
                OffsetDateTime.parse("2026-03-25T10:00:00-03:00"),
                OffsetDateTime.parse("2026-03-25T10:00:00-03:00"),
                OffsetDateTime.parse("2026-03-25T11:00:00-03:00"),
                3600
        );

        InventoryRepository inventoryRepository = new InventoryRepository(jdbcClient);
        listTypesService = new ListTypesService(
                new InventoryAccessService(inventoryRepository),
                new TypeRepository(jdbcClient)
        );
    }

    /**
     * Verifica que o servico lista os tipos do inventario ordenados por `type_id`.
     * Entrada: inventario acessivel com dois tipos persistidos.
     * Esperado: pagina com itens ordenados e sem `nextOffset` no fim da lista.
     */
    @Test
    void shouldListTypesOrderedByTypeId() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 2);
        insertType(2L, "Alimentos", false, inventoryId);
        insertType(1L, "Bebidas", true, inventoryId);

        ListTypesPage page = listTypesService.listTypes(authenticatedUser, inventoryId, null, null);

        assertEquals(
                List.of(1L, 2L),
                page.types().stream().map(ListTypesItemResponse::typeId).toList()
        );
        assertEquals("Bebidas", page.types().get(0).nome());
        assertEquals(true, page.types().get(0).hasImage());
        assertNull(page.nextOffset());
    }

    /**
     * Verifica que o servico calcula a continuidade da paginacao quando ha mais tipos.
     * Entrada: inventario com dois tipos e requisicao com `limit = 1`.
     * Esperado: pagina com um item e `nextOffset = 1`.
     */
    @Test
    void shouldReturnNextOffsetWhenThereAreMoreTypes() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 1);
        insertType(1L, "Bebidas", true, inventoryId);
        insertType(2L, "Alimentos", false, inventoryId);

        ListTypesPage page = listTypesService.listTypes(authenticatedUser, inventoryId, 1, 0);

        assertEquals(1, page.types().size());
        assertEquals(1, page.nextOffset());
        assertEquals(1, page.limit());
    }

    /**
     * Verifica que o servico rejeita inventario sem acesso para o usuario autenticado.
     * Entrada: inventario existente sem vinculo do usuario autenticado.
     * Esperado: NotFoundException associada ao campo `inv_id`.
     */
    @Test
    void shouldRejectWhenAuthenticatedUserDoesNotBelongToInventory() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");

        NotFoundException exception = assertThrows(
                NotFoundException.class,
                () -> listTypesService.listTypes(authenticatedUser, inventoryId, null, null)
        );

        assertEquals("inv_id", exception.getCampo());
        assertEquals("inventory not found", exception.getInfo());
    }

    /**
     * Verifica que o servico rejeita `offset` apos o fim da lista.
     * Entrada: inventario com um unico tipo e requisicao com `offset = 1`.
     * Esperado: NotFoundException associada ao campo `offset`.
     */
    @Test
    void shouldRejectOffsetAfterEndOfList() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 0);
        insertType(1L, "Bebidas", true, inventoryId);

        NotFoundException exception = assertThrows(
                NotFoundException.class,
                () -> listTypesService.listTypes(authenticatedUser, inventoryId, 10, 1)
        );

        assertEquals("offset", exception.getCampo());
        assertEquals("offset after end of list", exception.getInfo());
    }

    /**
     * Verifica que o servico rejeita `limit` fora do intervalo aceito.
     * Entrada: requisicao com `limit = 201`.
     * Esperado: NotFoundException associada ao campo `limit`.
     */
    @Test
    void shouldRejectLimitOutsideAcceptedRange() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 0);

        NotFoundException exception = assertThrows(
                NotFoundException.class,
                () -> listTypesService.listTypes(authenticatedUser, inventoryId, 201, 0)
        );

        assertEquals("limit", exception.getCampo());
        assertEquals("limit must be between 1 and 200", exception.getInfo());
    }

    private void insertUser(UUID userId, String name, String login) {
        jdbcClient.sql("""
                INSERT INTO users (user_id, name, login, passwd)
                VALUES (:userId, :name, :login, :passwd)
                """)
                .param("userId", userId)
                .param("name", name)
                .param("login", login)
                .param("passwd", "$2a$10$abcdefghijklmnopqrstuv")
                .update();
    }

    private void insertInventory(UUID inventoryId, String inventoryName) {
        jdbcClient.sql("""
                INSERT INTO inventories (inv_id, inv_name)
                VALUES (:inventoryId, :inventoryName)
                """)
                .param("inventoryId", inventoryId)
                .param("inventoryName", inventoryName)
                .update();
    }

    private void insertInventoryAccess(UUID userId, UUID inventoryId, int role) {
        jdbcClient.sql("""
                INSERT INTO inventory_access (user_id, inv_id, role)
                VALUES (:userId, :inventoryId, :role)
                """)
                .param("userId", userId)
                .param("inventoryId", inventoryId)
                .param("role", role)
                .update();
    }

    private void insertType(long typeId, String nome, boolean hasImage, UUID inventoryId) {
        jdbcClient.sql("""
                INSERT INTO types (type_id, nome, imagem, inv_id)
                VALUES (:typeId, :nome, :imagem, :inventoryId)
                """)
                .param("typeId", typeId)
                .param("nome", nome)
                .param("imagem", hasImage ? new byte[]{1, 2, 3} : null)
                .param("inventoryId", inventoryId)
                .update();
    }

    private DataSource createDataSource() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:list_types_service;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("test");
        return dataSource;
    }
}
