package br.com.cuscrudrest.products.get;

import br.com.cuscrudrest.auth.security.AuthenticatedUserPrincipal;
import br.com.cuscrudrest.common.error.NotFoundException;
import br.com.cuscrudrest.inventories.InventoryAccessService;
import br.com.cuscrudrest.inventories.InventoryRepository;
import br.com.cuscrudrest.products.ProductRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.time.OffsetDateTime;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

class GetProductServiceTest {

    private JdbcClient jdbcClient;
    private GetProductService getProductService;
    private AuthenticatedUserPrincipal authenticatedUser;

    /**
     * Prepara o schema minimo e as dependencias reais do servico de leitura unitaria de produtos.
     * Entrada: nenhuma.
     * Esperado: servico pronto para buscar um produto de inventario acessivel.
     */
    @BeforeEach
    void setUp() {
        DataSource dataSource = createDataSource();
        jdbcClient = JdbcClient.create(dataSource);
        jdbcClient.sql("DROP TABLE IF EXISTS products").update();
        jdbcClient.sql("DROP TABLE IF EXISTS types").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventory_access").update();
        jdbcClient.sql("DROP TABLE IF EXISTS inventories").update();
        jdbcClient.sql("DROP TABLE IF EXISTS users").update();
        jdbcClient.sql("""
                CREATE TABLE users (
                    user_id UUID PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    login VARCHAR(255) UNIQUE NOT NULL,
                    passwd TEXT NOT NULL,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventories (
                    inv_id UUID PRIMARY KEY,
                    inv_name VARCHAR(255) NOT NULL
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE inventory_access (
                    user_id UUID NOT NULL,
                    inv_id UUID NOT NULL,
                    role INT NOT NULL,
                    PRIMARY KEY (user_id, inv_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE types (
                    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nome VARCHAR(255) NOT NULL,
                    imagem BYTEA NULL,
                    inv_id UUID NOT NULL,
                    UNIQUE (inv_id, type_id)
                )
                """).update();
        jdbcClient.sql("""
                CREATE TABLE products (
                    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    type_id BIGINT NOT NULL,
                    marca VARCHAR(255) NULL,
                    dataValidade TIMESTAMP WITH TIME ZONE NULL,
                    unidade BIGINT NULL,
                    unidadeMedida VARCHAR(255) NULL,
                    quantidade BIGINT NOT NULL DEFAULT 0,
                    inv_id UUID NOT NULL,
                    FOREIGN KEY (inv_id, type_id) REFERENCES types(inv_id, type_id) ON DELETE RESTRICT
                )
                """).update();

        UUID userId = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
        insertUser(userId, "Joao Silva", "joao@example.com");
        authenticatedUser = new AuthenticatedUserPrincipal(
                userId,
                "Joao Silva",
                "joao@example.com",
                OffsetDateTime.parse("2026-03-25T10:00:00-03:00"),
                OffsetDateTime.parse("2026-03-25T10:00:00-03:00"),
                OffsetDateTime.parse("2026-03-25T11:00:00-03:00"),
                3600
        );

        InventoryRepository inventoryRepository = new InventoryRepository(jdbcClient);
        getProductService = new GetProductService(
                new InventoryAccessService(inventoryRepository),
                new ProductRepository(jdbcClient)
        );
    }

    /**
     * Verifica que o servico retorna um produto especifico do inventario informado.
     * Entrada: inventario acessivel com produto persistido.
     * Esperado: resposta com todos os campos previstos pela API.
     */
    @Test
    void shouldReturnProductWhenItExistsInInventory() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        OffsetDateTime validade = OffsetDateTime.parse("2026-12-31T00:00:00-03:00");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 2);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(101L, 1L, "Acme", validade, 1L, "un", 50L, inventoryId);

        GetProductResponse response = getProductService.getProduct(authenticatedUser, inventoryId, 101L);

        assertEquals(101L, response.productId());
        assertEquals(1L, response.typeId());
        assertEquals("Acme", response.marca());
        assertEquals(validade, response.dataValidade());
        assertEquals(1L, response.unidade());
        assertEquals("un", response.unidadeMedida());
        assertEquals(50L, response.quantidade());
        assertEquals(inventoryId, response.inventoryId());
    }

    /**
     * Verifica que o servico preserva campos nulos opcionais ao retornar o produto.
     * Entrada: inventario acessivel com produto sem marca, validade e unidade.
     * Esperado: resposta com campos opcionais nulos.
     */
    @Test
    void shouldReturnNullOptionalFieldsWhenProductDoesNotPopulateThem() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 1);
        insertType(1L, "Bebidas", inventoryId);
        insertProduct(101L, 1L, null, null, null, null, 50L, inventoryId);

        GetProductResponse response = getProductService.getProduct(authenticatedUser, inventoryId, 101L);

        assertNull(response.marca());
        assertNull(response.dataValidade());
        assertNull(response.unidade());
        assertNull(response.unidadeMedida());
    }

    /**
     * Verifica que o servico rejeita inventario sem acesso para o usuario autenticado.
     * Entrada: inventario existente sem vinculo do usuario autenticado.
     * Esperado: NotFoundException associada ao campo `inv_id`.
     */
    @Test
    void shouldRejectWhenAuthenticatedUserDoesNotBelongToInventory() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");

        NotFoundException exception = assertThrows(
                NotFoundException.class,
                () -> getProductService.getProduct(authenticatedUser, inventoryId, 101L)
        );

        assertEquals("inv_id", exception.getCampo());
        assertEquals("inventory not found", exception.getInfo());
    }

    /**
     * Verifica que o servico rejeita `product_id` inexistente para o inventario informado.
     * Entrada: inventario acessivel sem produto correspondente.
     * Esperado: NotFoundException associada ao campo `product_id`.
     */
    @Test
    void shouldRejectWhenProductDoesNotExist() {
        UUID inventoryId = UUID.fromString("123e4567-e89b-12d3-a456-426614174000");
        insertInventory(inventoryId, "Estoque da Loja");
        insertInventoryAccess(authenticatedUser.userId(), inventoryId, 0);

        NotFoundException exception = assertThrows(
                NotFoundException.class,
                () -> getProductService.getProduct(authenticatedUser, inventoryId, 101L)
        );

        assertEquals("product_id", exception.getCampo());
        assertEquals("product not found", exception.getInfo());
    }

    private void insertUser(UUID userId, String name, String login) {
        jdbcClient.sql("""
                INSERT INTO users (user_id, name, login, passwd)
                VALUES (:userId, :name, :login, :passwd)
                """)
                .param("userId", userId)
                .param("name", name)
                .param("login", login)
                .param("passwd", "$2a$10$abcdefghijklmnopqrstuv")
                .update();
    }

    private void insertInventory(UUID inventoryId, String inventoryName) {
        jdbcClient.sql("""
                INSERT INTO inventories (inv_id, inv_name)
                VALUES (:inventoryId, :inventoryName)
                """)
                .param("inventoryId", inventoryId)
                .param("inventoryName", inventoryName)
                .update();
    }

    private void insertInventoryAccess(UUID userId, UUID inventoryId, int role) {
        jdbcClient.sql("""
                INSERT INTO inventory_access (user_id, inv_id, role)
                VALUES (:userId, :inventoryId, :role)
                """)
                .param("userId", userId)
                .param("inventoryId", inventoryId)
                .param("role", role)
                .update();
    }

    private void insertType(long typeId, String nome, UUID inventoryId) {
        jdbcClient.sql("""
                INSERT INTO types (type_id, nome, inv_id)
                VALUES (:typeId, :nome, :inventoryId)
                """)
                .param("typeId", typeId)
                .param("nome", nome)
                .param("inventoryId", inventoryId)
                .update();
    }

    private void insertProduct(
            long productId,
            long typeId,
            String marca,
            OffsetDateTime dataValidade,
            Long unidade,
            String unidadeMedida,
            long quantidade,
            UUID inventoryId
    ) {
        jdbcClient.sql("""
                INSERT INTO products (
                    product_id, type_id, marca, dataValidade, unidade, unidadeMedida, quantidade, inv_id
                ) VALUES (
                    :productId, :typeId, :marca, :dataValidade, :unidade, :unidadeMedida, :quantidade, :inventoryId
                )
                """)
                .param("productId", productId)
                .param("typeId", typeId)
                .param("marca", marca)
                .param("dataValidade", dataValidade)
                .param("unidade", unidade)
                .param("unidadeMedida", unidadeMedida)
                .param("quantidade", quantidade)
                .param("inventoryId", inventoryId)
                .update();
    }

    private DataSource createDataSource() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:get_product_service;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("test");
        return dataSource;
    }
}
